apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatra-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yatra-app
  template:
    metadata:
      labels:
        app: yatra-app
    spec:
      containers:
      - name: yatra-app
        image: varunihk/yatra-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yatra-app-service
spec:
  selector:
    app: yatra-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
