name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: varunihk/yatra-app:latest

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/kubernetes-deployment.yaml
